version: "3.7"

services:
  datascience-notebook:
    image: huazhou/lange_symposium_workshop_2022:latest
    volumes:
      - "/Users/huazhou/Documents/Box\ Sync/MIMIC/mimic-iv-1.0:/srv/mimic-iv"
    ports:
      - 8888:8888
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - webnet
networks:
  webnet: 
